### ISSUE TITLE
Remove the settings after switching to non-knob stories

### ISSUE THREAD

**Issue by vidaaudrey** [storybook-eol/storybook-addon-knobs#23]
Just tried this addon, it's awesome. I've been looking for something like this for long time. Thanks for the great work!

A tiny problem is that when I switch to non-knob stories, the knob settings pane doesn't go away.  
![image](https://cloud.githubusercontent.com/assets/10999093/18425021/7ec09aec-786a-11e6-9802-b3105346ea5c.png)
![image](https://cloud.githubusercontent.com/assets/10999093/18425027/8e7e9bf0-786a-11e6-80d8-46a3b4207f22.png)

**Comment by arunoda** [comment]
Yep. That's true.
I assume we can do a fix for that.

CC @roonyh

**Comment by roonyh** [comment]
@vidaaudrey This will not happen when even the non-knob stories are also decorated with the `withKnobs` decorator.

Easiest way to decorate all the stories with the `withKnobs` decorator is adding it globally inside the `.storybook/config.js` file.

```js
import {
  withKnobs
} from '@kadira/storybook-addon-knobs';

addDecorator(withKnobs);
configure....
```

**Comment by vidaaudrey** [comment]
@roonyh  thanks very much for the quick answer.  Will do that for now, but hope this could be fix as not all components need the decorator.

**Comment by arunoda** [comment]
@vidaaudrey Actually, that decorator does nothing and that's the way we detect knobs.

**Comment by arunoda** [comment]
@roonyh additionally can't we try using `api.onStory` on the panel and clear knobs?

**Comment by roonyh** [comment]
@arunoda I tried that. Then "NO KNOBS" will be displayed for a moment when switching between stories before new knobs load. Looks a little ugly. I guess we can wait a bit with `setTimeout` to see if a new story with knobs will load before clearing current ones, but that feels messy.

**Comment by arunoda** [comment]
@roonyh hmmm. 
Could you start a branch on that. Let's give it a try.
`setTimeout` is definitely ugly.

**Comment by roonyh** [comment]
@arunoda Sure.

**Comment by roonyh** [comment]
@arunoda Pushed a new branch: [clear-knobs-on-story](https://github.com/kadirahq/storybook-addon-knobs/tree/clear-knobs-on-story)

**Comment by arunoda** [comment]
I'll try to see what we can do about this.

**Comment by bholloway** [comment]
Thanks for the workaround, it worked out well for me. I anticipate most of my stories will use knobs so no harm making it global.

However it prompts me to ask about story **lifecycle**...

I am in the unfortunate position where I have to monkey-patch certain dependencies for my component. And I need to do this based on the knobs values. Ideally I want to patch when I enter the story and un-patch when I leave the story.

Seems I can only access knobs values inside the `add()`ed render function. Right now I am idempotently patching in the render function, and not un-patching. Works for now but I can see problems long-term.

It seems like knobs is perhaps suffering similar lifecycle issues. Would this warrant some lifecycle hooks? `setup()` / `teardown()` sort of thing.

One would not want to encourage this sort of thing - the rest of the API is nicely functional. However some of us have a mutable legacy to deal with.

**Comment by roonyh** [comment]
@bholloway This is something I have given some thought while trying to cope with this problem.

Thanks for the suggestion of a story lifecycle. It does make sense. Storybook powered setup / teardown steps indeed would help knobs to get rid of the wrapper completely. Probably some other addons will benefit as well.

This will require some large changes in storybook. We are planing to start a discussion for storybook version 3 soon. We can develop on this suggestion there.
