### ISSUE TITLE
Possible to just use defaultProps as input for knobs?

### ISSUE THREAD

**Issue by kevinSuttle** [storybook-eol/storybook-addon-knobs#30]
See also: 
https://github.com/kadirahq/storybook-addon-knobs/commit/2f12de4a94bee358c6676072292e1356965ad4b3

https://github.com/kadirahq/react-storybook-addon-info/issues/35

Seems a bit error-prone to write them out each time. 

Example: 

`theme={select('Theme', ['Light', 'Dark'], 'Light')}`

when this is defined as: 

``` jsx
theme: React.PropTypes.oneOf(['Light, Dark'])
...

Button.defaultProps = {
  theme: "Light"
}
```

**Comment by arunoda** [comment]
I think we can do it, but the detecting types would be a problem.
But, in the above case, if we write it like this, I hope we can fix our code to use the default props somehow.

~~~
theme={select('Theme', ['Light', 'Dark'])} 
~~~

Is that what you are referring to?

**Comment by kevinSuttle** [comment]
@arunoda You hit on it here. react-docgen does a lot of this and supports Flow. https://github.com/kadirahq/react-storybook-addon-info/issues/67#issuecomment-247491057

**Comment by lucasconstantino** [comment]
Some related work in progress: https://github.com/lucasconstantino/storybook-addon-smart-knobs
