### ISSUE TITLE
Remove UPPERCASE text-transform from labels

### ISSUE THREAD

**Issue by philcockfield** [storybook-eol/storybook-addon-knobs#53]
I understand stylistically the reason to put that transform on the property label, BUT with camelCase there is information contained with the name (the word-parts) that you are stomping out by applying this style.  It's valid and helpful information for the developer working with the knobs:

![image](https://cloud.githubusercontent.com/assets/185555/19067731/f20575c2-8a7b-11e6-9d1b-56ee2ae6e271.png)

It would be great if you reset this to display as the actual name of the property!  Digging knobs, nice work!

**Comment by arunoda** [comment]
I get the point. Happy to accept to a PR :)

**Comment by philcockfield** [comment]
Ha ha!  "Happy to accept to a PR :)" should be a keyboard shortcut.  I'll take a look.  

Also, want to talk about the index selector on StoryBook itself.  Is that a pluggable module - there's some improvements I'd like to make to it.  What's the feasibility of that?

**Comment by arunoda** [comment]
What's index selector?
If that's something new, let's discuss in a new issue.

**Comment by philcockfield** [comment]
Hey @arunoda - I was referring to this when I said "index selector":

![image](https://cloud.githubusercontent.com/assets/185555/19165827/c7d10072-8c61-11e6-8558-be63d49c3222.png)

But that's not `knobs`, or even this issue, so I'll start a new issue on the `storybook` repo.  

- What do you refer to that panel as?
- What's the best repo to put that on (I think you've isolated the UI parts of StoryBook out somewhere, right?)

**Comment by arunoda** [comment]
Yep. It's on the Storybook UI repo.
That's not pluggable yet.
But we want to customize it (To show stories only for changed snapshots).
Currently, there no plans on how we should do it.
