### ISSUE TITLE
Values Bleeding Between Stories

### ISSUE THREAD

**Issue by philcockfield** [storybook-eol/storybook-addon-knobs#55]
I have two stories that load two different components that both have a `size` property.
If I have a knob for setting that size like so:

```
// For component-1
size={knobs.number('size', 60)}

// For component-2
size={knobs.number('size', 12)}
```

When I load component-2, I'm seeing the component-1 value of 60.

This is on ReactNative, not sure if that makes a difference.  Also, possibly related to this, there is a little bit of weirdness when jumping between stories with the knobs panel not re-rendering to represent the currently loaded stories knobs settings.

Thanks guys!

**Comment by arunoda** [comment]
@philcockfield may be that's something with RN. 
@roonyh could you check that and bring onStory knobs clear feature soon.

**Comment by arunoda** [comment]
@philcockfield we have looked into this it's RN only.
We do knobs config stuff only when the component rendered for the first time.
In React Storybook, this is not a problem since it's always render by clearing the old story.

That's not the case in RN. We don't do that.
So, now we are trying to clear the old story when switching stories.
If not we'll do something.

I hope @roonyh could something about this today or tomorrow.

**Comment by roonyh** [comment]
@philcockfield I just published rn-storybook v2.1.4 with the fix in kadirahq/react-native-storybook#104. It makes sure that a story is mounted completely.

This should probably fix the issues you describe. Could you try updating rn-storybook to 2.1.4 and try it out?

**Comment by wordofchristian** [comment]
I can confirm this occurs with react web as well, not just react native. The query strings seem to persist when switching between stories. It also continues to show the knobs from the previous story on the new one (even if the new story doesn't have any knobs). This creates a confusing UI experience.

**Comment by ChristopherBiscardi** [comment]
@wordofchristian I'm also seeing this (on web) due to the lack of clearing the query params

**Comment by wordofchristian** [comment]
@ChristopherBiscardi I was able to partially solve it by adding the `withKnobs` decorator to my global storybook config

```javascript
import {  addDecorator } from '@kadira/storybook';
import { withKnobs } from '@kadira/storybook-addon-knobs';
// add global knobs decorator to fix issue of persistent values between stories
addDecorator(withKnobs);
```

**Comment by sbaggott** [comment]
This is definitely an issue with react web. We are using the withKnobs decorator in our code, but it doesn't prevent the issue with persistent values in the query strings.
