### ISSUE TITLE
Discussion: data flow from components to knobs.

### ISSUE THREAD

**Issue by kevinSuttle** [storybook-eol/storybook-addon-knobs#58]
Specifically: [Controlled vs Uncontrolled](https://facebook.github.io/react/docs/forms.html#controlled-components) 

Seems to be the typical one-way, top-down `props` via knobs down into components. 

Repro: 

``` js
<textArea
          placeholder={text('placeholder', "Don't use placeholder text in place of labels")}
          value={text('value', '')}
          onChange={action('TextArea changed')}
          onFocus={action('TextArea focused')}
          onBlur={action('TextArea un-focused')}
          disabled={boolean('disabled', false)}
        />
```

Typing in a `value` won't change the knobs, because this isn't how React works (no two-way binding). 

Just wondering if there is a better UX for this. 
We tend to use Storybook and knobs to allow our designers to stress test UI components.
This behavior (while not the primary concern of Kadira 😄 ) can be a bit confusing. 

Thanks all. Love the work you're doing.

**Comment by arunoda** [comment]
How about if we have a way to update the value of knob. So then you can plug that in somehow for the onChange.

**Comment by kevinSuttle** [comment]
Ah that makes sense!

**Comment by arunoda** [comment]
I'll play with a pattern for this.
