### ISSUE TITLE
select knob seems backwards

### ISSUE THREAD

**Issue by lifehackett** [storybook-eol/storybook-addon-knobs#71]
Every time I use the `select` knob object syntax I write it incorrectly, but it also is more limiting.  IMO it makes more sense that the dropdown would show the keys and on selection pass the value.  

Additionally, the current setup restricts what can be passed as the prop value to strings or numbers because object keys are more restricted.  i.e. you can't have a function or an object in the key position, but you could in the value.

I realize this would be a breaking change.

**Comment by webOS101** [comment]
Add to this that you cannot set `null` as a key, either.  I went through some of our stories and found cases where people expected that they could use `'null': null` inside the select.  Needless to say, it doesn't work that way.

**Comment by bluetidepro** [comment]
YES. Please fix this. It makes 0 sense why it was done this way. It is completely backwards.

**Comment by ndbroadbent** [comment]
Oh yeah, I was just wondering why my numbers were all getting converted to strings. I was using this:

```js
select('Size', { 4: 4, 6: 6, 9: 9 }, 4)
```

This definitely feels backwards. The main reason is because when you use this syntax, your keys must be strings, but the values can be any type.
