### ISSUE TITLE
Empty strings

### ISSUE THREAD

**Issue by mmintel** [storybook-eol/storybook-addon-knobs#73]
Hi!

```
href={text('href', undefined)}
```

works perfectly until I enter some text and delete it again. instead of removing my href prop it fills in an empty string. Which I don't really understand because, normally, react will remove the prop if its empty (right?).

So initially my component looks like
```
<Button .. />
```

and after editing href and deleting again it looks like
```
<Button href="" />
```

Is this a bug or do I use it the wrong way?

My component passes the href prop immediately to the attribute like this here:
```
href={href}
```

Cheers!

**Comment by renatorib** [comment]
Will be nice if have something link this:
```jsx
<Button href={text.optional('href', 'http://google.com')} />
```

When uses with `.option` can appear a checkbox in front of textfield, to enable/disable this.
When disabled, it pass `undefined` to value, and when enabled it pass the textfield value.

**Comment by Djspaceg** [comment]
@renatorib's proposal would work well for `select` as well, which could add an initial blank to the `<select>` which when chosen would exclude the prop from being sent to the component.

**Comment by renatorib** [comment]
Unfortunately storybook's repos are almost abandoned. =(

**Comment by Djspaceg** [comment]
For others interested in this problem (in the future), here's our solution:
```
/*
 *
 * Use for props that can take null value so that Storybook doesn't complain.
 * example use:
 * `nullify(select('propName', [null, 'value', 'two']))`
 * `nullify(select('propName', ['', 'value', 'two']))`
 *
*/

const nullify = (v) => v === '' ? null : v;

export default nullify;
```

This allows a story author to identify knobs that need to be treated differently than always-convert-to-empty-string, i.e. `null` support cases. Simply use it like this in a story:
```
import nullify from '../src/utils/nullify.js';
...
<Slider
    orientation={nullify(select('orientation', [null, 'vertical', 'radial']))}
>
```
The prop will even be omitted in the storybook component info screen when the `null` option is selected, just like you'd expect. `select`s render the `null` as a blank (no text) in the dropdown for that item. Also, because the developer must intentionally add it, it's not going to break existing stories that expect empty strings.

**Comment by renatorib** [comment]
@Djspaceg great!

**Comment by Djspaceg** [comment]
Just last week I realized it would be nice to incorporate strict equality to false, which would remove optional props from appearing in the "info" addon too. You could apply nullify to Boolean props:

Things like `<Button round>Basic</Button>` will not appear as `<Button round={false}>Basic</Button>` but instead as simply `<Button>Basic</Button>`.
```
const nullify = (v) => (v === '' || v === false) ? null : v;
```
or even smaller:
```
const nullify = (v) => !v ? null : v;
```
