### ISSUE TITLE
hits history.pushState limits in Storybook 2+

### ISSUE THREAD

**Issue by gmarinov** [storybook-eol/storybook-addon-knobs#91]
please see attached gif

![knobs](https://cloud.githubusercontent.com/assets/14101296/23683305/260d2616-0390-11e7-85c7-3a6e868ccd04.gif)

not sure if this is a storybook or knobs bug.

browser: Safari 10, OSX 10.12
expected: reasonable not to push state before mouse is released?
actual: pushes on slider input, hitting browser limit

**Comment by andrewpeterprifer** [comment]
I have the same issue. It makes the slider effectively useless. Would it be possible to debounce the calls to pushState?
