### ISSUE TITLE
How to rerender story via change props in action?

### ISSUE THREAD

**Issue by zaqqaz** [storybook-eol/storybook-addon-knobs#96]
I'd like to dynamicly change some props after some actions, e.g. after click:
```
<MyComponent 
   opened={boolean("Opened", true)}
   onClick={() => boolean("Opened", false)}}
 />
```
As i see knobs value changed but, willReciveProps was not triggered.

Actually now i see only one way, create additional component-container for story book, but i hope should be more friendly way :)

**Comment by kurumkan** [comment]
Please - any comments on how to force the component to rerender on props change.

**Comment by ndelangen** [comment]
@kurumkan Please make an issue here:
https://github.com/storybooks/storybook
